// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer_user.grpc.proto

package com.wanpng.employer.grpc.domain;

/**
 * Protobuf type {@code protos.domain.EmployerUserGrpc}
 */
public final class EmployerUserGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.EmployerUserGrpc)
    EmployerUserGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployerUserGrpc.newBuilder() to construct.
  private EmployerUserGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployerUserGrpc() {
    id_ = "";
    employerId_ = "";
    userFirstName_ = "";
    userLastName_ = "";
    email_ = "";
    createdBy_ = "";
    createdWhen_ = "";
    updatedBy_ = "";
    updatedWhen_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployerUserGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployerUserGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            employerId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userFirstName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userLastName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            createdBy_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            createdWhen_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            updatedBy_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            updatedWhen_ = s;
            break;
          }
          case 80: {

            isActive_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.internal_static_protos_domain_EmployerUserGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.internal_static_protos_domain_EmployerUserGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.employer.grpc.domain.EmployerUserGrpc.class, com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object employerId_;
  /**
   * <code>string employer_id = 2;</code>
   * @return The employerId.
   */
  @java.lang.Override
  public java.lang.String getEmployerId() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employerId_ = s;
      return s;
    }
  }
  /**
   * <code>string employer_id = 2;</code>
   * @return The bytes for employerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployerIdBytes() {
    java.lang.Object ref = employerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIRST_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object userFirstName_;
  /**
   * <code>string user_first_name = 3;</code>
   * @return The userFirstName.
   */
  @java.lang.Override
  public java.lang.String getUserFirstName() {
    java.lang.Object ref = userFirstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userFirstName_ = s;
      return s;
    }
  }
  /**
   * <code>string user_first_name = 3;</code>
   * @return The bytes for userFirstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserFirstNameBytes() {
    java.lang.Object ref = userFirstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userFirstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_LAST_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object userLastName_;
  /**
   * <code>string user_last_name = 4;</code>
   * @return The userLastName.
   */
  @java.lang.Override
  public java.lang.String getUserLastName() {
    java.lang.Object ref = userLastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userLastName_ = s;
      return s;
    }
  }
  /**
   * <code>string user_last_name = 4;</code>
   * @return The bytes for userLastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserLastNameBytes() {
    java.lang.Object ref = userLastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 5;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_BY_FIELD_NUMBER = 6;
  private volatile java.lang.Object createdBy_;
  /**
   * <code>string created_by = 6;</code>
   * @return The createdBy.
   */
  @java.lang.Override
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string created_by = 6;</code>
   * @return The bytes for createdBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_WHEN_FIELD_NUMBER = 7;
  private volatile java.lang.Object createdWhen_;
  /**
   * <code>string created_when = 7;</code>
   * @return The createdWhen.
   */
  @java.lang.Override
  public java.lang.String getCreatedWhen() {
    java.lang.Object ref = createdWhen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdWhen_ = s;
      return s;
    }
  }
  /**
   * <code>string created_when = 7;</code>
   * @return The bytes for createdWhen.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedWhenBytes() {
    java.lang.Object ref = createdWhen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdWhen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_BY_FIELD_NUMBER = 8;
  private volatile java.lang.Object updatedBy_;
  /**
   * <code>string updated_by = 8;</code>
   * @return The updatedBy.
   */
  @java.lang.Override
  public java.lang.String getUpdatedBy() {
    java.lang.Object ref = updatedBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedBy_ = s;
      return s;
    }
  }
  /**
   * <code>string updated_by = 8;</code>
   * @return The bytes for updatedBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedByBytes() {
    java.lang.Object ref = updatedBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_WHEN_FIELD_NUMBER = 9;
  private volatile java.lang.Object updatedWhen_;
  /**
   * <code>string updated_when = 9;</code>
   * @return The updatedWhen.
   */
  @java.lang.Override
  public java.lang.String getUpdatedWhen() {
    java.lang.Object ref = updatedWhen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedWhen_ = s;
      return s;
    }
  }
  /**
   * <code>string updated_when = 9;</code>
   * @return The bytes for updatedWhen.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedWhenBytes() {
    java.lang.Object ref = updatedWhen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedWhen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_ACTIVE_FIELD_NUMBER = 10;
  private boolean isActive_;
  /**
   * <code>bool is_active = 10;</code>
   * @return The isActive.
   */
  @java.lang.Override
  public boolean getIsActive() {
    return isActive_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getEmployerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, employerId_);
    }
    if (!getUserFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userFirstName_);
    }
    if (!getUserLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userLastName_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, email_);
    }
    if (!getCreatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createdBy_);
    }
    if (!getCreatedWhenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, createdWhen_);
    }
    if (!getUpdatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, updatedBy_);
    }
    if (!getUpdatedWhenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, updatedWhen_);
    }
    if (isActive_ != false) {
      output.writeBool(10, isActive_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getEmployerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, employerId_);
    }
    if (!getUserFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userFirstName_);
    }
    if (!getUserLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userLastName_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, email_);
    }
    if (!getCreatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createdBy_);
    }
    if (!getCreatedWhenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, createdWhen_);
    }
    if (!getUpdatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, updatedBy_);
    }
    if (!getUpdatedWhenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, updatedWhen_);
    }
    if (isActive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isActive_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.employer.grpc.domain.EmployerUserGrpc)) {
      return super.equals(obj);
    }
    com.wanpng.employer.grpc.domain.EmployerUserGrpc other = (com.wanpng.employer.grpc.domain.EmployerUserGrpc) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getEmployerId()
        .equals(other.getEmployerId())) return false;
    if (!getUserFirstName()
        .equals(other.getUserFirstName())) return false;
    if (!getUserLastName()
        .equals(other.getUserLastName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getCreatedBy()
        .equals(other.getCreatedBy())) return false;
    if (!getCreatedWhen()
        .equals(other.getCreatedWhen())) return false;
    if (!getUpdatedBy()
        .equals(other.getUpdatedBy())) return false;
    if (!getUpdatedWhen()
        .equals(other.getUpdatedWhen())) return false;
    if (getIsActive()
        != other.getIsActive()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + EMPLOYER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEmployerId().hashCode();
    hash = (37 * hash) + USER_FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserFirstName().hashCode();
    hash = (37 * hash) + USER_LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserLastName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + CREATED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    hash = (37 * hash) + CREATED_WHEN_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedWhen().hashCode();
    hash = (37 * hash) + UPDATED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedBy().hashCode();
    hash = (37 * hash) + UPDATED_WHEN_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedWhen().hashCode();
    hash = (37 * hash) + IS_ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsActive());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.employer.grpc.domain.EmployerUserGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.EmployerUserGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.EmployerUserGrpc)
      com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.internal_static_protos_domain_EmployerUserGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.internal_static_protos_domain_EmployerUserGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.employer.grpc.domain.EmployerUserGrpc.class, com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder.class);
    }

    // Construct using com.wanpng.employer.grpc.domain.EmployerUserGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      employerId_ = "";

      userFirstName_ = "";

      userLastName_ = "";

      email_ = "";

      createdBy_ = "";

      createdWhen_ = "";

      updatedBy_ = "";

      updatedWhen_ = "";

      isActive_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.internal_static_protos_domain_EmployerUserGrpc_descriptor;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerUserGrpc getDefaultInstanceForType() {
      return com.wanpng.employer.grpc.domain.EmployerUserGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerUserGrpc build() {
      com.wanpng.employer.grpc.domain.EmployerUserGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerUserGrpc buildPartial() {
      com.wanpng.employer.grpc.domain.EmployerUserGrpc result = new com.wanpng.employer.grpc.domain.EmployerUserGrpc(this);
      result.id_ = id_;
      result.employerId_ = employerId_;
      result.userFirstName_ = userFirstName_;
      result.userLastName_ = userLastName_;
      result.email_ = email_;
      result.createdBy_ = createdBy_;
      result.createdWhen_ = createdWhen_;
      result.updatedBy_ = updatedBy_;
      result.updatedWhen_ = updatedWhen_;
      result.isActive_ = isActive_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.employer.grpc.domain.EmployerUserGrpc) {
        return mergeFrom((com.wanpng.employer.grpc.domain.EmployerUserGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.employer.grpc.domain.EmployerUserGrpc other) {
      if (other == com.wanpng.employer.grpc.domain.EmployerUserGrpc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getEmployerId().isEmpty()) {
        employerId_ = other.employerId_;
        onChanged();
      }
      if (!other.getUserFirstName().isEmpty()) {
        userFirstName_ = other.userFirstName_;
        onChanged();
      }
      if (!other.getUserLastName().isEmpty()) {
        userLastName_ = other.userLastName_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        onChanged();
      }
      if (!other.getCreatedWhen().isEmpty()) {
        createdWhen_ = other.createdWhen_;
        onChanged();
      }
      if (!other.getUpdatedBy().isEmpty()) {
        updatedBy_ = other.updatedBy_;
        onChanged();
      }
      if (!other.getUpdatedWhen().isEmpty()) {
        updatedWhen_ = other.updatedWhen_;
        onChanged();
      }
      if (other.getIsActive() != false) {
        setIsActive(other.getIsActive());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.employer.grpc.domain.EmployerUserGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.employer.grpc.domain.EmployerUserGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object employerId_ = "";
    /**
     * <code>string employer_id = 2;</code>
     * @return The employerId.
     */
    public java.lang.String getEmployerId() {
      java.lang.Object ref = employerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employer_id = 2;</code>
     * @return The bytes for employerId.
     */
    public com.google.protobuf.ByteString
        getEmployerIdBytes() {
      java.lang.Object ref = employerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employer_id = 2;</code>
     * @param value The employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerId() {
      
      employerId_ = getDefaultInstance().getEmployerId();
      onChanged();
      return this;
    }
    /**
     * <code>string employer_id = 2;</code>
     * @param value The bytes for employerId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employerId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userFirstName_ = "";
    /**
     * <code>string user_first_name = 3;</code>
     * @return The userFirstName.
     */
    public java.lang.String getUserFirstName() {
      java.lang.Object ref = userFirstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userFirstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_first_name = 3;</code>
     * @return The bytes for userFirstName.
     */
    public com.google.protobuf.ByteString
        getUserFirstNameBytes() {
      java.lang.Object ref = userFirstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userFirstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_first_name = 3;</code>
     * @param value The userFirstName to set.
     * @return This builder for chaining.
     */
    public Builder setUserFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userFirstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_first_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserFirstName() {
      
      userFirstName_ = getDefaultInstance().getUserFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string user_first_name = 3;</code>
     * @param value The bytes for userFirstName to set.
     * @return This builder for chaining.
     */
    public Builder setUserFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userFirstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userLastName_ = "";
    /**
     * <code>string user_last_name = 4;</code>
     * @return The userLastName.
     */
    public java.lang.String getUserLastName() {
      java.lang.Object ref = userLastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_last_name = 4;</code>
     * @return The bytes for userLastName.
     */
    public com.google.protobuf.ByteString
        getUserLastNameBytes() {
      java.lang.Object ref = userLastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_last_name = 4;</code>
     * @param value The userLastName to set.
     * @return This builder for chaining.
     */
    public Builder setUserLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userLastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_last_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserLastName() {
      
      userLastName_ = getDefaultInstance().getUserLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string user_last_name = 4;</code>
     * @param value The bytes for userLastName to set.
     * @return This builder for chaining.
     */
    public Builder setUserLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userLastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 5;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 5;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 5;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 5;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string created_by = 6;</code>
     * @return The createdBy.
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_by = 6;</code>
     * @return The bytes for createdBy.
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_by = 6;</code>
     * @param value The createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 6;</code>
     * @param value The bytes for createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdWhen_ = "";
    /**
     * <code>string created_when = 7;</code>
     * @return The createdWhen.
     */
    public java.lang.String getCreatedWhen() {
      java.lang.Object ref = createdWhen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdWhen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_when = 7;</code>
     * @return The bytes for createdWhen.
     */
    public com.google.protobuf.ByteString
        getCreatedWhenBytes() {
      java.lang.Object ref = createdWhen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdWhen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_when = 7;</code>
     * @param value The createdWhen to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedWhen(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdWhen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created_when = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedWhen() {
      
      createdWhen_ = getDefaultInstance().getCreatedWhen();
      onChanged();
      return this;
    }
    /**
     * <code>string created_when = 7;</code>
     * @param value The bytes for createdWhen to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedWhenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdWhen_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatedBy_ = "";
    /**
     * <code>string updated_by = 8;</code>
     * @return The updatedBy.
     */
    public java.lang.String getUpdatedBy() {
      java.lang.Object ref = updatedBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string updated_by = 8;</code>
     * @return The bytes for updatedBy.
     */
    public com.google.protobuf.ByteString
        getUpdatedByBytes() {
      java.lang.Object ref = updatedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string updated_by = 8;</code>
     * @param value The updatedBy to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string updated_by = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedBy() {
      
      updatedBy_ = getDefaultInstance().getUpdatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string updated_by = 8;</code>
     * @param value The bytes for updatedBy to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedBy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatedWhen_ = "";
    /**
     * <code>string updated_when = 9;</code>
     * @return The updatedWhen.
     */
    public java.lang.String getUpdatedWhen() {
      java.lang.Object ref = updatedWhen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedWhen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string updated_when = 9;</code>
     * @return The bytes for updatedWhen.
     */
    public com.google.protobuf.ByteString
        getUpdatedWhenBytes() {
      java.lang.Object ref = updatedWhen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedWhen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string updated_when = 9;</code>
     * @param value The updatedWhen to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedWhen(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedWhen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string updated_when = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedWhen() {
      
      updatedWhen_ = getDefaultInstance().getUpdatedWhen();
      onChanged();
      return this;
    }
    /**
     * <code>string updated_when = 9;</code>
     * @param value The bytes for updatedWhen to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedWhenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedWhen_ = value;
      onChanged();
      return this;
    }

    private boolean isActive_ ;
    /**
     * <code>bool is_active = 10;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }
    /**
     * <code>bool is_active = 10;</code>
     * @param value The isActive to set.
     * @return This builder for chaining.
     */
    public Builder setIsActive(boolean value) {
      
      isActive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_active = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsActive() {
      
      isActive_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.EmployerUserGrpc)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.EmployerUserGrpc)
  private static final com.wanpng.employer.grpc.domain.EmployerUserGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.employer.grpc.domain.EmployerUserGrpc();
  }

  public static com.wanpng.employer.grpc.domain.EmployerUserGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployerUserGrpc>
      PARSER = new com.google.protobuf.AbstractParser<EmployerUserGrpc>() {
    @java.lang.Override
    public EmployerUserGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployerUserGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployerUserGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployerUserGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerUserGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

