// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer_user.grpc.proto

package com.wanpng.employer.grpc.domain;

public interface EmployerUserGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.EmployerUserGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string employer_id = 2;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 2;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string user_first_name = 3;</code>
   * @return The userFirstName.
   */
  java.lang.String getUserFirstName();
  /**
   * <code>string user_first_name = 3;</code>
   * @return The bytes for userFirstName.
   */
  com.google.protobuf.ByteString
      getUserFirstNameBytes();

  /**
   * <code>string user_last_name = 4;</code>
   * @return The userLastName.
   */
  java.lang.String getUserLastName();
  /**
   * <code>string user_last_name = 4;</code>
   * @return The bytes for userLastName.
   */
  com.google.protobuf.ByteString
      getUserLastNameBytes();
}
