// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.employer.grpc.domain;

public interface EmployerGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.EmployerGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string website_url = 3;</code>
   * @return The websiteUrl.
   */
  java.lang.String getWebsiteUrl();
  /**
   * <code>string website_url = 3;</code>
   * @return The bytes for websiteUrl.
   */
  com.google.protobuf.ByteString
      getWebsiteUrlBytes();

  /**
   * <code>string industry = 4;</code>
   * @return The industry.
   */
  java.lang.String getIndustry();
  /**
   * <code>string industry = 4;</code>
   * @return The bytes for industry.
   */
  com.google.protobuf.ByteString
      getIndustryBytes();

  /**
   * <code>string photo_url = 5;</code>
   * @return The photoUrl.
   */
  java.lang.String getPhotoUrl();
  /**
   * <code>string photo_url = 5;</code>
   * @return The bytes for photoUrl.
   */
  com.google.protobuf.ByteString
      getPhotoUrlBytes();

  /**
   * <code>string company_phone_number = 6;</code>
   * @return The companyPhoneNumber.
   */
  java.lang.String getCompanyPhoneNumber();
  /**
   * <code>string company_phone_number = 6;</code>
   * @return The bytes for companyPhoneNumber.
   */
  com.google.protobuf.ByteString
      getCompanyPhoneNumberBytes();

  /**
   * <code>string company_address = 7;</code>
   * @return The companyAddress.
   */
  java.lang.String getCompanyAddress();
  /**
   * <code>string company_address = 7;</code>
   * @return The bytes for companyAddress.
   */
  com.google.protobuf.ByteString
      getCompanyAddressBytes();

  /**
   * <code>string company_information = 8;</code>
   * @return The companyInformation.
   */
  java.lang.String getCompanyInformation();
  /**
   * <code>string company_information = 8;</code>
   * @return The bytes for companyInformation.
   */
  com.google.protobuf.ByteString
      getCompanyInformationBytes();

  /**
   * <code>bool is_lanco = 9;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();
}
