// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.employer.grpc.domain;

/**
 * Protobuf type {@code protos.domain.EmployerGrpc}
 */
public final class EmployerGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.EmployerGrpc)
    EmployerGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployerGrpc.newBuilder() to construct.
  private EmployerGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployerGrpc() {
    id_ = "";
    companyName_ = "";
    websiteUrl_ = "";
    industry_ = "";
    photoUrl_ = "";
    companyPhoneNumber_ = "";
    companyAddress_ = "";
    companyInformation_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployerGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployerGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            companyName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            websiteUrl_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            industry_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            photoUrl_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            companyPhoneNumber_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            companyAddress_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            companyInformation_ = s;
            break;
          }
          case 72: {

            isLanco_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.employer.grpc.domain.EmployerGrpcProtos.internal_static_protos_domain_EmployerGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.employer.grpc.domain.EmployerGrpcProtos.internal_static_protos_domain_EmployerGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.employer.grpc.domain.EmployerGrpc.class, com.wanpng.employer.grpc.domain.EmployerGrpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object companyName_;
  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  @java.lang.Override
  public java.lang.String getCompanyName() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyName_ = s;
      return s;
    }
  }
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyNameBytes() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEBSITE_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object websiteUrl_;
  /**
   * <code>string website_url = 3;</code>
   * @return The websiteUrl.
   */
  @java.lang.Override
  public java.lang.String getWebsiteUrl() {
    java.lang.Object ref = websiteUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      websiteUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string website_url = 3;</code>
   * @return The bytes for websiteUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWebsiteUrlBytes() {
    java.lang.Object ref = websiteUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      websiteUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDUSTRY_FIELD_NUMBER = 4;
  private volatile java.lang.Object industry_;
  /**
   * <code>string industry = 4;</code>
   * @return The industry.
   */
  @java.lang.Override
  public java.lang.String getIndustry() {
    java.lang.Object ref = industry_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      industry_ = s;
      return s;
    }
  }
  /**
   * <code>string industry = 4;</code>
   * @return The bytes for industry.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIndustryBytes() {
    java.lang.Object ref = industry_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      industry_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHOTO_URL_FIELD_NUMBER = 5;
  private volatile java.lang.Object photoUrl_;
  /**
   * <code>string photo_url = 5;</code>
   * @return The photoUrl.
   */
  @java.lang.Override
  public java.lang.String getPhotoUrl() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      photoUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string photo_url = 5;</code>
   * @return The bytes for photoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhotoUrlBytes() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      photoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_PHONE_NUMBER_FIELD_NUMBER = 6;
  private volatile java.lang.Object companyPhoneNumber_;
  /**
   * <code>string company_phone_number = 6;</code>
   * @return The companyPhoneNumber.
   */
  @java.lang.Override
  public java.lang.String getCompanyPhoneNumber() {
    java.lang.Object ref = companyPhoneNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyPhoneNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string company_phone_number = 6;</code>
   * @return The bytes for companyPhoneNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyPhoneNumberBytes() {
    java.lang.Object ref = companyPhoneNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyPhoneNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_ADDRESS_FIELD_NUMBER = 7;
  private volatile java.lang.Object companyAddress_;
  /**
   * <code>string company_address = 7;</code>
   * @return The companyAddress.
   */
  @java.lang.Override
  public java.lang.String getCompanyAddress() {
    java.lang.Object ref = companyAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string company_address = 7;</code>
   * @return The bytes for companyAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyAddressBytes() {
    java.lang.Object ref = companyAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_INFORMATION_FIELD_NUMBER = 8;
  private volatile java.lang.Object companyInformation_;
  /**
   * <code>string company_information = 8;</code>
   * @return The companyInformation.
   */
  @java.lang.Override
  public java.lang.String getCompanyInformation() {
    java.lang.Object ref = companyInformation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyInformation_ = s;
      return s;
    }
  }
  /**
   * <code>string company_information = 8;</code>
   * @return The bytes for companyInformation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyInformationBytes() {
    java.lang.Object ref = companyInformation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyInformation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_LANCO_FIELD_NUMBER = 9;
  private boolean isLanco_;
  /**
   * <code>bool is_lanco = 9;</code>
   * @return The isLanco.
   */
  @java.lang.Override
  public boolean getIsLanco() {
    return isLanco_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, companyName_);
    }
    if (!getWebsiteUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, websiteUrl_);
    }
    if (!getIndustryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, industry_);
    }
    if (!getPhotoUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, photoUrl_);
    }
    if (!getCompanyPhoneNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, companyPhoneNumber_);
    }
    if (!getCompanyAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, companyAddress_);
    }
    if (!getCompanyInformationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, companyInformation_);
    }
    if (isLanco_ != false) {
      output.writeBool(9, isLanco_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, companyName_);
    }
    if (!getWebsiteUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, websiteUrl_);
    }
    if (!getIndustryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, industry_);
    }
    if (!getPhotoUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, photoUrl_);
    }
    if (!getCompanyPhoneNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, companyPhoneNumber_);
    }
    if (!getCompanyAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, companyAddress_);
    }
    if (!getCompanyInformationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, companyInformation_);
    }
    if (isLanco_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isLanco_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.employer.grpc.domain.EmployerGrpc)) {
      return super.equals(obj);
    }
    com.wanpng.employer.grpc.domain.EmployerGrpc other = (com.wanpng.employer.grpc.domain.EmployerGrpc) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCompanyName()
        .equals(other.getCompanyName())) return false;
    if (!getWebsiteUrl()
        .equals(other.getWebsiteUrl())) return false;
    if (!getIndustry()
        .equals(other.getIndustry())) return false;
    if (!getPhotoUrl()
        .equals(other.getPhotoUrl())) return false;
    if (!getCompanyPhoneNumber()
        .equals(other.getCompanyPhoneNumber())) return false;
    if (!getCompanyAddress()
        .equals(other.getCompanyAddress())) return false;
    if (!getCompanyInformation()
        .equals(other.getCompanyInformation())) return false;
    if (getIsLanco()
        != other.getIsLanco()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyName().hashCode();
    hash = (37 * hash) + WEBSITE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getWebsiteUrl().hashCode();
    hash = (37 * hash) + INDUSTRY_FIELD_NUMBER;
    hash = (53 * hash) + getIndustry().hashCode();
    hash = (37 * hash) + PHOTO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPhotoUrl().hashCode();
    hash = (37 * hash) + COMPANY_PHONE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyPhoneNumber().hashCode();
    hash = (37 * hash) + COMPANY_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyAddress().hashCode();
    hash = (37 * hash) + COMPANY_INFORMATION_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyInformation().hashCode();
    hash = (37 * hash) + IS_LANCO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLanco());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.domain.EmployerGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.employer.grpc.domain.EmployerGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.EmployerGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.EmployerGrpc)
      com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.employer.grpc.domain.EmployerGrpcProtos.internal_static_protos_domain_EmployerGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.employer.grpc.domain.EmployerGrpcProtos.internal_static_protos_domain_EmployerGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.employer.grpc.domain.EmployerGrpc.class, com.wanpng.employer.grpc.domain.EmployerGrpc.Builder.class);
    }

    // Construct using com.wanpng.employer.grpc.domain.EmployerGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      companyName_ = "";

      websiteUrl_ = "";

      industry_ = "";

      photoUrl_ = "";

      companyPhoneNumber_ = "";

      companyAddress_ = "";

      companyInformation_ = "";

      isLanco_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.employer.grpc.domain.EmployerGrpcProtos.internal_static_protos_domain_EmployerGrpc_descriptor;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerGrpc getDefaultInstanceForType() {
      return com.wanpng.employer.grpc.domain.EmployerGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerGrpc build() {
      com.wanpng.employer.grpc.domain.EmployerGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.domain.EmployerGrpc buildPartial() {
      com.wanpng.employer.grpc.domain.EmployerGrpc result = new com.wanpng.employer.grpc.domain.EmployerGrpc(this);
      result.id_ = id_;
      result.companyName_ = companyName_;
      result.websiteUrl_ = websiteUrl_;
      result.industry_ = industry_;
      result.photoUrl_ = photoUrl_;
      result.companyPhoneNumber_ = companyPhoneNumber_;
      result.companyAddress_ = companyAddress_;
      result.companyInformation_ = companyInformation_;
      result.isLanco_ = isLanco_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.employer.grpc.domain.EmployerGrpc) {
        return mergeFrom((com.wanpng.employer.grpc.domain.EmployerGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.employer.grpc.domain.EmployerGrpc other) {
      if (other == com.wanpng.employer.grpc.domain.EmployerGrpc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCompanyName().isEmpty()) {
        companyName_ = other.companyName_;
        onChanged();
      }
      if (!other.getWebsiteUrl().isEmpty()) {
        websiteUrl_ = other.websiteUrl_;
        onChanged();
      }
      if (!other.getIndustry().isEmpty()) {
        industry_ = other.industry_;
        onChanged();
      }
      if (!other.getPhotoUrl().isEmpty()) {
        photoUrl_ = other.photoUrl_;
        onChanged();
      }
      if (!other.getCompanyPhoneNumber().isEmpty()) {
        companyPhoneNumber_ = other.companyPhoneNumber_;
        onChanged();
      }
      if (!other.getCompanyAddress().isEmpty()) {
        companyAddress_ = other.companyAddress_;
        onChanged();
      }
      if (!other.getCompanyInformation().isEmpty()) {
        companyInformation_ = other.companyInformation_;
        onChanged();
      }
      if (other.getIsLanco() != false) {
        setIsLanco(other.getIsLanco());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.employer.grpc.domain.EmployerGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.employer.grpc.domain.EmployerGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyName_ = "";
    /**
     * <code>string company_name = 2;</code>
     * @return The companyName.
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @return The bytes for companyName.
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyName() {
      
      companyName_ = getDefaultInstance().getCompanyName();
      onChanged();
      return this;
    }
    /**
     * <code>string company_name = 2;</code>
     * @param value The bytes for companyName to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object websiteUrl_ = "";
    /**
     * <code>string website_url = 3;</code>
     * @return The websiteUrl.
     */
    public java.lang.String getWebsiteUrl() {
      java.lang.Object ref = websiteUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        websiteUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string website_url = 3;</code>
     * @return The bytes for websiteUrl.
     */
    public com.google.protobuf.ByteString
        getWebsiteUrlBytes() {
      java.lang.Object ref = websiteUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        websiteUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string website_url = 3;</code>
     * @param value The websiteUrl to set.
     * @return This builder for chaining.
     */
    public Builder setWebsiteUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      websiteUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string website_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWebsiteUrl() {
      
      websiteUrl_ = getDefaultInstance().getWebsiteUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string website_url = 3;</code>
     * @param value The bytes for websiteUrl to set.
     * @return This builder for chaining.
     */
    public Builder setWebsiteUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      websiteUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object industry_ = "";
    /**
     * <code>string industry = 4;</code>
     * @return The industry.
     */
    public java.lang.String getIndustry() {
      java.lang.Object ref = industry_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        industry_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string industry = 4;</code>
     * @return The bytes for industry.
     */
    public com.google.protobuf.ByteString
        getIndustryBytes() {
      java.lang.Object ref = industry_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        industry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string industry = 4;</code>
     * @param value The industry to set.
     * @return This builder for chaining.
     */
    public Builder setIndustry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      industry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string industry = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndustry() {
      
      industry_ = getDefaultInstance().getIndustry();
      onChanged();
      return this;
    }
    /**
     * <code>string industry = 4;</code>
     * @param value The bytes for industry to set.
     * @return This builder for chaining.
     */
    public Builder setIndustryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      industry_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object photoUrl_ = "";
    /**
     * <code>string photo_url = 5;</code>
     * @return The photoUrl.
     */
    public java.lang.String getPhotoUrl() {
      java.lang.Object ref = photoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        photoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string photo_url = 5;</code>
     * @return The bytes for photoUrl.
     */
    public com.google.protobuf.ByteString
        getPhotoUrlBytes() {
      java.lang.Object ref = photoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        photoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string photo_url = 5;</code>
     * @param value The photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photoUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string photo_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhotoUrl() {
      
      photoUrl_ = getDefaultInstance().getPhotoUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string photo_url = 5;</code>
     * @param value The bytes for photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      photoUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyPhoneNumber_ = "";
    /**
     * <code>string company_phone_number = 6;</code>
     * @return The companyPhoneNumber.
     */
    public java.lang.String getCompanyPhoneNumber() {
      java.lang.Object ref = companyPhoneNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyPhoneNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_phone_number = 6;</code>
     * @return The bytes for companyPhoneNumber.
     */
    public com.google.protobuf.ByteString
        getCompanyPhoneNumberBytes() {
      java.lang.Object ref = companyPhoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyPhoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_phone_number = 6;</code>
     * @param value The companyPhoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyPhoneNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyPhoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_phone_number = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyPhoneNumber() {
      
      companyPhoneNumber_ = getDefaultInstance().getCompanyPhoneNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string company_phone_number = 6;</code>
     * @param value The bytes for companyPhoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyPhoneNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyAddress_ = "";
    /**
     * <code>string company_address = 7;</code>
     * @return The companyAddress.
     */
    public java.lang.String getCompanyAddress() {
      java.lang.Object ref = companyAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_address = 7;</code>
     * @return The bytes for companyAddress.
     */
    public com.google.protobuf.ByteString
        getCompanyAddressBytes() {
      java.lang.Object ref = companyAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_address = 7;</code>
     * @param value The companyAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_address = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyAddress() {
      
      companyAddress_ = getDefaultInstance().getCompanyAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string company_address = 7;</code>
     * @param value The bytes for companyAddress to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyInformation_ = "";
    /**
     * <code>string company_information = 8;</code>
     * @return The companyInformation.
     */
    public java.lang.String getCompanyInformation() {
      java.lang.Object ref = companyInformation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyInformation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company_information = 8;</code>
     * @return The bytes for companyInformation.
     */
    public com.google.protobuf.ByteString
        getCompanyInformationBytes() {
      java.lang.Object ref = companyInformation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyInformation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company_information = 8;</code>
     * @param value The companyInformation to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyInformation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyInformation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company_information = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyInformation() {
      
      companyInformation_ = getDefaultInstance().getCompanyInformation();
      onChanged();
      return this;
    }
    /**
     * <code>string company_information = 8;</code>
     * @param value The bytes for companyInformation to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyInformationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyInformation_ = value;
      onChanged();
      return this;
    }

    private boolean isLanco_ ;
    /**
     * <code>bool is_lanco = 9;</code>
     * @return The isLanco.
     */
    @java.lang.Override
    public boolean getIsLanco() {
      return isLanco_;
    }
    /**
     * <code>bool is_lanco = 9;</code>
     * @param value The isLanco to set.
     * @return This builder for chaining.
     */
    public Builder setIsLanco(boolean value) {
      
      isLanco_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_lanco = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLanco() {
      
      isLanco_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.EmployerGrpc)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.EmployerGrpc)
  private static final com.wanpng.employer.grpc.domain.EmployerGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.employer.grpc.domain.EmployerGrpc();
  }

  public static com.wanpng.employer.grpc.domain.EmployerGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployerGrpc>
      PARSER = new com.google.protobuf.AbstractParser<EmployerGrpc>() {
    @java.lang.Override
    public EmployerGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployerGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployerGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployerGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

