// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employer.grpc.proto

package com.wanpng.employer.grpc.domain;

public final class EmployerGrpcProtos {
  private EmployerGrpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_EmployerGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_EmployerGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protos/domain/employer.grpc.proto\022\rpro" +
      "tos.domain\"\320\001\n\014EmployerGrpc\022\n\n\002id\030\001 \001(\t\022" +
      "\024\n\014company_name\030\002 \001(\t\022\023\n\013website_url\030\003 \001" +
      "(\t\022\020\n\010industry\030\004 \001(\t\022\021\n\tphoto_url\030\005 \001(\t\022" +
      "\034\n\024company_phone_number\030\006 \001(\t\022\027\n\017company" +
      "_address\030\007 \001(\t\022\033\n\023company_information\030\010 " +
      "\001(\t\022\020\n\010is_lanco\030\t \001(\010Bm\n\037com.wanpng.empl" +
      "oyer.grpc.domainB\022EmployerGrpcProtosP\001Z4" +
      "github.com/wanpng/employers-profile-grpc" +
      "/grpc/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_EmployerGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_EmployerGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_EmployerGrpc_descriptor,
        new java.lang.String[] { "Id", "CompanyName", "WebsiteUrl", "Industry", "PhotoUrl", "CompanyPhoneNumber", "CompanyAddress", "CompanyInformation", "IsLanco", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
