// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public final class EmployerServiceProtos {
  private EmployerServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmployerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmployerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmployerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmployerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SearchEmployerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SearchEmployerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SearchEmployerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SearchEmployerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmployerUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmployerUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_UpdateEmployerUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_UpdateEmployerUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmployerUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmployerUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_UpdateEmployerUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_UpdateEmployerUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*protos/service/employer_service.grpc.p" +
      "roto\022\016protos.service\032!protos/domain/empl" +
      "oyer.grpc.proto\032&protos/domain/employer_" +
      "user.grpc.proto\")\n\022GetEmployerRequest\022\023\n" +
      "\013employer_id\030\001 \001(\t\"D\n\023GetEmployerRespons" +
      "e\022-\n\010employer\030\001 \001(\0132\033.protos.domain.Empl" +
      "oyerGrpc\">\n\025SearchEmployerRequest\022\024\n\014emp" +
      "loyer_ids\030\001 \003(\t\022\017\n\007keyword\030\002 \001(\t\".\n\026Sear" +
      "chEmployerResponse\022\024\n\014employer_ids\030\001 \003(\t" +
      "\")\n\026GetEmployerUserRequest\022\017\n\007user_id\030\001 " +
      "\001(\t\"S\n\031UpdateEmployerUserRequest\0226\n\rempl" +
      "oyer_user\030\001 \001(\0132\037.protos.domain.Employer" +
      "UserGrpc\"Q\n\027GetEmployerUserResponse\0226\n\re" +
      "mployer_user\030\001 \001(\0132\037.protos.domain.Emplo" +
      "yerUserGrpc\"-\n\032UpdateEmployerUserRespons" +
      "e\022\017\n\007user_id\030\001 \001(\t2\233\003\n\017EmployerService\022V" +
      "\n\013GetEmployer\022\".protos.service.GetEmploy" +
      "erRequest\032#.protos.service.GetEmployerRe" +
      "sponse\022_\n\016SearchEmployer\022%.protos.servic" +
      "e.SearchEmployerRequest\032&.protos.service" +
      ".SearchEmployerResponse\022b\n\017GetEmployerUs" +
      "er\022&.protos.service.GetEmployerUserReque" +
      "st\032\'.protos.service.GetEmployerUserRespo" +
      "nse\022k\n\022UpdateEmployerUser\022).protos.servi" +
      "ce.UpdateEmployerUserRequest\032*.protos.se" +
      "rvice.UpdateEmployerUserResponseBr\n com." +
      "wanpng.employer.grpc.serviceB\025EmployerSe" +
      "rviceProtosP\001Z5github.com/wanpng/employe" +
      "rs-profile-grpc/grpc/serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.employer.grpc.domain.EmployerGrpcProtos.getDescriptor(),
          com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.getDescriptor(),
        });
    internal_static_protos_service_GetEmployerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_GetEmployerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmployerRequest_descriptor,
        new java.lang.String[] { "EmployerId", });
    internal_static_protos_service_GetEmployerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_GetEmployerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmployerResponse_descriptor,
        new java.lang.String[] { "Employer", });
    internal_static_protos_service_SearchEmployerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_service_SearchEmployerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SearchEmployerRequest_descriptor,
        new java.lang.String[] { "EmployerIds", "Keyword", });
    internal_static_protos_service_SearchEmployerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_service_SearchEmployerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SearchEmployerResponse_descriptor,
        new java.lang.String[] { "EmployerIds", });
    internal_static_protos_service_GetEmployerUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_service_GetEmployerUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmployerUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_protos_service_UpdateEmployerUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_service_UpdateEmployerUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_UpdateEmployerUserRequest_descriptor,
        new java.lang.String[] { "EmployerUser", });
    internal_static_protos_service_GetEmployerUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protos_service_GetEmployerUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmployerUserResponse_descriptor,
        new java.lang.String[] { "EmployerUser", });
    internal_static_protos_service_UpdateEmployerUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protos_service_UpdateEmployerUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_UpdateEmployerUserResponse_descriptor,
        new java.lang.String[] { "UserId", });
    com.wanpng.employer.grpc.domain.EmployerGrpcProtos.getDescriptor();
    com.wanpng.employer.grpc.domain.EmployerUserGrpcProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
