// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public interface GetEmployerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetEmployerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   * @return Whether the employer field is set.
   */
  boolean hasEmployer();
  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   * @return The employer.
   */
  com.wanpng.employer.grpc.domain.EmployerGrpc getEmployer();
  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   */
  com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder getEmployerOrBuilder();
}
