// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

/**
 * Protobuf type {@code protos.service.GetEmployerResponse}
 */
public final class GetEmployerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.GetEmployerResponse)
    GetEmployerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetEmployerResponse.newBuilder() to construct.
  private GetEmployerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetEmployerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetEmployerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetEmployerResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.wanpng.employer.grpc.domain.EmployerGrpc.Builder subBuilder = null;
            if (employer_ != null) {
              subBuilder = employer_.toBuilder();
            }
            employer_ = input.readMessage(com.wanpng.employer.grpc.domain.EmployerGrpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(employer_);
              employer_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_GetEmployerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_GetEmployerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.employer.grpc.service.GetEmployerResponse.class, com.wanpng.employer.grpc.service.GetEmployerResponse.Builder.class);
  }

  public static final int EMPLOYER_FIELD_NUMBER = 1;
  private com.wanpng.employer.grpc.domain.EmployerGrpc employer_;
  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   * @return Whether the employer field is set.
   */
  @java.lang.Override
  public boolean hasEmployer() {
    return employer_ != null;
  }
  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   * @return The employer.
   */
  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerGrpc getEmployer() {
    return employer_ == null ? com.wanpng.employer.grpc.domain.EmployerGrpc.getDefaultInstance() : employer_;
  }
  /**
   * <code>.protos.domain.EmployerGrpc employer = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder getEmployerOrBuilder() {
    return getEmployer();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (employer_ != null) {
      output.writeMessage(1, getEmployer());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (employer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmployer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.employer.grpc.service.GetEmployerResponse)) {
      return super.equals(obj);
    }
    com.wanpng.employer.grpc.service.GetEmployerResponse other = (com.wanpng.employer.grpc.service.GetEmployerResponse) obj;

    if (hasEmployer() != other.hasEmployer()) return false;
    if (hasEmployer()) {
      if (!getEmployer()
          .equals(other.getEmployer())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmployer()) {
      hash = (37 * hash) + EMPLOYER_FIELD_NUMBER;
      hash = (53 * hash) + getEmployer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.GetEmployerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.employer.grpc.service.GetEmployerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.GetEmployerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.GetEmployerResponse)
      com.wanpng.employer.grpc.service.GetEmployerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_GetEmployerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_GetEmployerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.employer.grpc.service.GetEmployerResponse.class, com.wanpng.employer.grpc.service.GetEmployerResponse.Builder.class);
    }

    // Construct using com.wanpng.employer.grpc.service.GetEmployerResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (employerBuilder_ == null) {
        employer_ = null;
      } else {
        employer_ = null;
        employerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_GetEmployerResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.GetEmployerResponse getDefaultInstanceForType() {
      return com.wanpng.employer.grpc.service.GetEmployerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.GetEmployerResponse build() {
      com.wanpng.employer.grpc.service.GetEmployerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.GetEmployerResponse buildPartial() {
      com.wanpng.employer.grpc.service.GetEmployerResponse result = new com.wanpng.employer.grpc.service.GetEmployerResponse(this);
      if (employerBuilder_ == null) {
        result.employer_ = employer_;
      } else {
        result.employer_ = employerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.employer.grpc.service.GetEmployerResponse) {
        return mergeFrom((com.wanpng.employer.grpc.service.GetEmployerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.employer.grpc.service.GetEmployerResponse other) {
      if (other == com.wanpng.employer.grpc.service.GetEmployerResponse.getDefaultInstance()) return this;
      if (other.hasEmployer()) {
        mergeEmployer(other.getEmployer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.employer.grpc.service.GetEmployerResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.employer.grpc.service.GetEmployerResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wanpng.employer.grpc.domain.EmployerGrpc employer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.employer.grpc.domain.EmployerGrpc, com.wanpng.employer.grpc.domain.EmployerGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder> employerBuilder_;
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     * @return Whether the employer field is set.
     */
    public boolean hasEmployer() {
      return employerBuilder_ != null || employer_ != null;
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     * @return The employer.
     */
    public com.wanpng.employer.grpc.domain.EmployerGrpc getEmployer() {
      if (employerBuilder_ == null) {
        return employer_ == null ? com.wanpng.employer.grpc.domain.EmployerGrpc.getDefaultInstance() : employer_;
      } else {
        return employerBuilder_.getMessage();
      }
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public Builder setEmployer(com.wanpng.employer.grpc.domain.EmployerGrpc value) {
      if (employerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employer_ = value;
        onChanged();
      } else {
        employerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public Builder setEmployer(
        com.wanpng.employer.grpc.domain.EmployerGrpc.Builder builderForValue) {
      if (employerBuilder_ == null) {
        employer_ = builderForValue.build();
        onChanged();
      } else {
        employerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public Builder mergeEmployer(com.wanpng.employer.grpc.domain.EmployerGrpc value) {
      if (employerBuilder_ == null) {
        if (employer_ != null) {
          employer_ =
            com.wanpng.employer.grpc.domain.EmployerGrpc.newBuilder(employer_).mergeFrom(value).buildPartial();
        } else {
          employer_ = value;
        }
        onChanged();
      } else {
        employerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public Builder clearEmployer() {
      if (employerBuilder_ == null) {
        employer_ = null;
        onChanged();
      } else {
        employer_ = null;
        employerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public com.wanpng.employer.grpc.domain.EmployerGrpc.Builder getEmployerBuilder() {
      
      onChanged();
      return getEmployerFieldBuilder().getBuilder();
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    public com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder getEmployerOrBuilder() {
      if (employerBuilder_ != null) {
        return employerBuilder_.getMessageOrBuilder();
      } else {
        return employer_ == null ?
            com.wanpng.employer.grpc.domain.EmployerGrpc.getDefaultInstance() : employer_;
      }
    }
    /**
     * <code>.protos.domain.EmployerGrpc employer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.employer.grpc.domain.EmployerGrpc, com.wanpng.employer.grpc.domain.EmployerGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder> 
        getEmployerFieldBuilder() {
      if (employerBuilder_ == null) {
        employerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wanpng.employer.grpc.domain.EmployerGrpc, com.wanpng.employer.grpc.domain.EmployerGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerGrpcOrBuilder>(
                getEmployer(),
                getParentForChildren(),
                isClean());
        employer_ = null;
      }
      return employerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.GetEmployerResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.GetEmployerResponse)
  private static final com.wanpng.employer.grpc.service.GetEmployerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.employer.grpc.service.GetEmployerResponse();
  }

  public static com.wanpng.employer.grpc.service.GetEmployerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEmployerResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEmployerResponse>() {
    @java.lang.Override
    public GetEmployerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetEmployerResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetEmployerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEmployerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.employer.grpc.service.GetEmployerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

