// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public interface GetEmployerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetEmployerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();
}
