// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

/**
 * Protobuf type {@code protos.service.SearchEmployerResponse}
 */
public final class SearchEmployerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.SearchEmployerResponse)
    SearchEmployerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchEmployerResponse.newBuilder() to construct.
  private SearchEmployerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchEmployerResponse() {
    employerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchEmployerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchEmployerResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              employerIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            employerIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        employerIds_ = employerIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_SearchEmployerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_SearchEmployerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.employer.grpc.service.SearchEmployerResponse.class, com.wanpng.employer.grpc.service.SearchEmployerResponse.Builder.class);
  }

  public static final int EMPLOYER_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList employerIds_;
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @return A list containing the employerIds.
   */
  public com.google.protobuf.ProtocolStringList
      getEmployerIdsList() {
    return employerIds_;
  }
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @return The count of employerIds.
   */
  public int getEmployerIdsCount() {
    return employerIds_.size();
  }
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The employerIds at the given index.
   */
  public java.lang.String getEmployerIds(int index) {
    return employerIds_.get(index);
  }
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the employerIds at the given index.
   */
  public com.google.protobuf.ByteString
      getEmployerIdsBytes(int index) {
    return employerIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employerIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, employerIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < employerIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(employerIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEmployerIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.employer.grpc.service.SearchEmployerResponse)) {
      return super.equals(obj);
    }
    com.wanpng.employer.grpc.service.SearchEmployerResponse other = (com.wanpng.employer.grpc.service.SearchEmployerResponse) obj;

    if (!getEmployerIdsList()
        .equals(other.getEmployerIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployerIdsCount() > 0) {
      hash = (37 * hash) + EMPLOYER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getEmployerIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.SearchEmployerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.employer.grpc.service.SearchEmployerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.SearchEmployerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.SearchEmployerResponse)
      com.wanpng.employer.grpc.service.SearchEmployerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_SearchEmployerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_SearchEmployerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.employer.grpc.service.SearchEmployerResponse.class, com.wanpng.employer.grpc.service.SearchEmployerResponse.Builder.class);
    }

    // Construct using com.wanpng.employer.grpc.service.SearchEmployerResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_SearchEmployerResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.SearchEmployerResponse getDefaultInstanceForType() {
      return com.wanpng.employer.grpc.service.SearchEmployerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.SearchEmployerResponse build() {
      com.wanpng.employer.grpc.service.SearchEmployerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.SearchEmployerResponse buildPartial() {
      com.wanpng.employer.grpc.service.SearchEmployerResponse result = new com.wanpng.employer.grpc.service.SearchEmployerResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        employerIds_ = employerIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.employerIds_ = employerIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.employer.grpc.service.SearchEmployerResponse) {
        return mergeFrom((com.wanpng.employer.grpc.service.SearchEmployerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.employer.grpc.service.SearchEmployerResponse other) {
      if (other == com.wanpng.employer.grpc.service.SearchEmployerResponse.getDefaultInstance()) return this;
      if (!other.employerIds_.isEmpty()) {
        if (employerIds_.isEmpty()) {
          employerIds_ = other.employerIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEmployerIdsIsMutable();
          employerIds_.addAll(other.employerIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.employer.grpc.service.SearchEmployerResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.employer.grpc.service.SearchEmployerResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList employerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEmployerIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        employerIds_ = new com.google.protobuf.LazyStringArrayList(employerIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @return A list containing the employerIds.
     */
    public com.google.protobuf.ProtocolStringList
        getEmployerIdsList() {
      return employerIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @return The count of employerIds.
     */
    public int getEmployerIdsCount() {
      return employerIds_.size();
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The employerIds at the given index.
     */
    public java.lang.String getEmployerIds(int index) {
      return employerIds_.get(index);
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the employerIds at the given index.
     */
    public com.google.protobuf.ByteString
        getEmployerIdsBytes(int index) {
      return employerIds_.getByteString(index);
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The employerIds to set.
     * @return This builder for chaining.
     */
    public Builder setEmployerIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmployerIdsIsMutable();
      employerIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param value The employerIds to add.
     * @return This builder for chaining.
     */
    public Builder addEmployerIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmployerIdsIsMutable();
      employerIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param values The employerIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllEmployerIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureEmployerIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, employerIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployerIds() {
      employerIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string employer_ids = 1;</code>
     * @param value The bytes of the employerIds to add.
     * @return This builder for chaining.
     */
    public Builder addEmployerIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEmployerIdsIsMutable();
      employerIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.SearchEmployerResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.SearchEmployerResponse)
  private static final com.wanpng.employer.grpc.service.SearchEmployerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.employer.grpc.service.SearchEmployerResponse();
  }

  public static com.wanpng.employer.grpc.service.SearchEmployerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchEmployerResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchEmployerResponse>() {
    @java.lang.Override
    public SearchEmployerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchEmployerResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchEmployerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchEmployerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.employer.grpc.service.SearchEmployerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

