// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public interface UpdateEmployerUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.UpdateEmployerUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.EmployerUserGrpc user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.protos.domain.EmployerUserGrpc user = 1;</code>
   * @return The user.
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpc getUser();
  /**
   * <code>.protos.domain.EmployerUserGrpc user = 1;</code>
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder getUserOrBuilder();
}
