// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

/**
 * Protobuf type {@code protos.service.UpdateEmployerUserRequest}
 */
public final class UpdateEmployerUserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.UpdateEmployerUserRequest)
    UpdateEmployerUserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateEmployerUserRequest.newBuilder() to construct.
  private UpdateEmployerUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateEmployerUserRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateEmployerUserRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateEmployerUserRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder subBuilder = null;
            if (employerUser_ != null) {
              subBuilder = employerUser_.toBuilder();
            }
            employerUser_ = input.readMessage(com.wanpng.employer.grpc.domain.EmployerUserGrpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(employerUser_);
              employerUser_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_UpdateEmployerUserRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_UpdateEmployerUserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.class, com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.Builder.class);
  }

  public static final int EMPLOYER_USER_FIELD_NUMBER = 1;
  private com.wanpng.employer.grpc.domain.EmployerUserGrpc employerUser_;
  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   * @return Whether the employerUser field is set.
   */
  @java.lang.Override
  public boolean hasEmployerUser() {
    return employerUser_ != null;
  }
  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   * @return The employerUser.
   */
  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerUserGrpc getEmployerUser() {
    return employerUser_ == null ? com.wanpng.employer.grpc.domain.EmployerUserGrpc.getDefaultInstance() : employerUser_;
  }
  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder getEmployerUserOrBuilder() {
    return getEmployerUser();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (employerUser_ != null) {
      output.writeMessage(1, getEmployerUser());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (employerUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmployerUser());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.employer.grpc.service.UpdateEmployerUserRequest)) {
      return super.equals(obj);
    }
    com.wanpng.employer.grpc.service.UpdateEmployerUserRequest other = (com.wanpng.employer.grpc.service.UpdateEmployerUserRequest) obj;

    if (hasEmployerUser() != other.hasEmployerUser()) return false;
    if (hasEmployerUser()) {
      if (!getEmployerUser()
          .equals(other.getEmployerUser())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmployerUser()) {
      hash = (37 * hash) + EMPLOYER_USER_FIELD_NUMBER;
      hash = (53 * hash) + getEmployerUser().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.employer.grpc.service.UpdateEmployerUserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.UpdateEmployerUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.UpdateEmployerUserRequest)
      com.wanpng.employer.grpc.service.UpdateEmployerUserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_UpdateEmployerUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_UpdateEmployerUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.class, com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.Builder.class);
    }

    // Construct using com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (employerUserBuilder_ == null) {
        employerUser_ = null;
      } else {
        employerUser_ = null;
        employerUserBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.employer.grpc.service.EmployerServiceProtos.internal_static_protos_service_UpdateEmployerUserRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.UpdateEmployerUserRequest getDefaultInstanceForType() {
      return com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.UpdateEmployerUserRequest build() {
      com.wanpng.employer.grpc.service.UpdateEmployerUserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.employer.grpc.service.UpdateEmployerUserRequest buildPartial() {
      com.wanpng.employer.grpc.service.UpdateEmployerUserRequest result = new com.wanpng.employer.grpc.service.UpdateEmployerUserRequest(this);
      if (employerUserBuilder_ == null) {
        result.employerUser_ = employerUser_;
      } else {
        result.employerUser_ = employerUserBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.employer.grpc.service.UpdateEmployerUserRequest) {
        return mergeFrom((com.wanpng.employer.grpc.service.UpdateEmployerUserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.employer.grpc.service.UpdateEmployerUserRequest other) {
      if (other == com.wanpng.employer.grpc.service.UpdateEmployerUserRequest.getDefaultInstance()) return this;
      if (other.hasEmployerUser()) {
        mergeEmployerUser(other.getEmployerUser());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.employer.grpc.service.UpdateEmployerUserRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.employer.grpc.service.UpdateEmployerUserRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wanpng.employer.grpc.domain.EmployerUserGrpc employerUser_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.employer.grpc.domain.EmployerUserGrpc, com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder> employerUserBuilder_;
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     * @return Whether the employerUser field is set.
     */
    public boolean hasEmployerUser() {
      return employerUserBuilder_ != null || employerUser_ != null;
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     * @return The employerUser.
     */
    public com.wanpng.employer.grpc.domain.EmployerUserGrpc getEmployerUser() {
      if (employerUserBuilder_ == null) {
        return employerUser_ == null ? com.wanpng.employer.grpc.domain.EmployerUserGrpc.getDefaultInstance() : employerUser_;
      } else {
        return employerUserBuilder_.getMessage();
      }
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public Builder setEmployerUser(com.wanpng.employer.grpc.domain.EmployerUserGrpc value) {
      if (employerUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employerUser_ = value;
        onChanged();
      } else {
        employerUserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public Builder setEmployerUser(
        com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder builderForValue) {
      if (employerUserBuilder_ == null) {
        employerUser_ = builderForValue.build();
        onChanged();
      } else {
        employerUserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public Builder mergeEmployerUser(com.wanpng.employer.grpc.domain.EmployerUserGrpc value) {
      if (employerUserBuilder_ == null) {
        if (employerUser_ != null) {
          employerUser_ =
            com.wanpng.employer.grpc.domain.EmployerUserGrpc.newBuilder(employerUser_).mergeFrom(value).buildPartial();
        } else {
          employerUser_ = value;
        }
        onChanged();
      } else {
        employerUserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public Builder clearEmployerUser() {
      if (employerUserBuilder_ == null) {
        employerUser_ = null;
        onChanged();
      } else {
        employerUser_ = null;
        employerUserBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder getEmployerUserBuilder() {
      
      onChanged();
      return getEmployerUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    public com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder getEmployerUserOrBuilder() {
      if (employerUserBuilder_ != null) {
        return employerUserBuilder_.getMessageOrBuilder();
      } else {
        return employerUser_ == null ?
            com.wanpng.employer.grpc.domain.EmployerUserGrpc.getDefaultInstance() : employerUser_;
      }
    }
    /**
     * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.employer.grpc.domain.EmployerUserGrpc, com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder> 
        getEmployerUserFieldBuilder() {
      if (employerUserBuilder_ == null) {
        employerUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wanpng.employer.grpc.domain.EmployerUserGrpc, com.wanpng.employer.grpc.domain.EmployerUserGrpc.Builder, com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder>(
                getEmployerUser(),
                getParentForChildren(),
                isClean());
        employerUser_ = null;
      }
      return employerUserBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.UpdateEmployerUserRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.UpdateEmployerUserRequest)
  private static final com.wanpng.employer.grpc.service.UpdateEmployerUserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.employer.grpc.service.UpdateEmployerUserRequest();
  }

  public static com.wanpng.employer.grpc.service.UpdateEmployerUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateEmployerUserRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateEmployerUserRequest>() {
    @java.lang.Override
    public UpdateEmployerUserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateEmployerUserRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateEmployerUserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateEmployerUserRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.employer.grpc.service.UpdateEmployerUserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

