// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public interface UpdateEmployerUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.UpdateEmployerUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   * @return Whether the employerUser field is set.
   */
  boolean hasEmployerUser();
  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   * @return The employerUser.
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpc getEmployerUser();
  /**
   * <code>.protos.domain.EmployerUserGrpc employer_user = 1;</code>
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder getEmployerUserOrBuilder();
}
