// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employer.grpc.service;

public interface UpdateEmployerUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.UpdateEmployerUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.EmployerUserGrpc id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.protos.domain.EmployerUserGrpc id = 1;</code>
   * @return The id.
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpc getId();
  /**
   * <code>.protos.domain.EmployerUserGrpc id = 1;</code>
   */
  com.wanpng.employer.grpc.domain.EmployerUserGrpcOrBuilder getIdOrBuilder();
}
